### ISSUE TITLE
Black formatter

### ISSUE THREAD

**Issue by jklaise** [SeldonIO/alibi#102]
Investigate usage of the opinionated code formatter: https://github.com/python/black

**Comment by axsauze** [comment]
+1 
Widely recommended, and helps resolve disputes on best practices around formatting if introduced correctly in the development process

**Comment by jklaise** [comment]
@axsaucedo experimented with Black on some of the source code, it does some strange splits of iterables (different from what I expected from their playground). Not sure if it is a sign of verbosity on our side.

**Comment by axsaucedo** [comment]
@jklaise what was the code (and resulting format) that you experienced this with?

**Comment by jklaise** [comment]
Closing as there hasn't been concensus and the current formatting + linters is working well.
