### ISSUE TITLE
Too many mandatory dependencies

### ISSUE THREAD

**Issue by jamesmyatt** [SeldonIO/alibi#103]
This looks like it could be a great package, but it has too many mandatory dependencies to be appropriate for general use. Can you move them to "extras" or support packages, please?

https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies

**Comment by jklaise** [comment]
Thank you for your interest in the library! I appreciate that we are a bit heavy on the dependencies, but we would need to think carefully which packages to split out as it would make several algorithms not work out-of-the-box for all use cases (e.g. we use `tensorflow` internally for optimization, `opencv-python` for downloading image datasets and `spacy` for NLP corpus use cases. One option would be to try split the dependencies across use cases, e.g. to enable `nlp` one could install `alibi[nlp]` or for image usecases `alibi[cv]`. Did you have any particular thoughts about this?

**Comment by jamesmyatt** [comment]
Using opencv-python just to download datasets seems like overkill, but otherwise that's pretty much what I had in mind. Dask is a pretty good example of doing this, using both extras (https://github.com/dask/dask/blob/master/setup.py) and subsidiary packages: (e.g. https://github.com/dask/dask-ml, https://github.com/dask/dask-xgboost)

It's also worth considering that, if people want to explain keras models, then they will already have keras installed, so it may not be necessary to have it as an explicit extra.

If you're using tensorflow internally, then clearly it's OK to have that as an install dependency. Although if it's only used for a small subset of the functionality, then it might still be worth having as an extra, like some tools do for their CLI (e.g. https://github.com/theskumar/python-dotenv/blob/master/setup.py).

**Comment by jklaise** [comment]
Thanks for the feedback, I'm working on stripping out some of the unnecessary deps. For image downloading we can probably go with `PIL` instead of `opencv` which is much lighter.

**Comment by jklaise** [comment]
@jamesmyatt I've slimmed down the package a little in [v0.2.1](https://github.com/SeldonIO/alibi/releases/tag/v0.2.1). For now we will not split it up depending on the use case, but this might change as the functionality grows and the API stabilises. Probably the heaviest dependency is `tensorflow`, it's quite key for some of the underlying optimization algorithms, but on the other hand not every method will use it. I will keep this issue open for now for further discussion.

**Comment by jklaise** [comment]
Will close for now as currently running a fairly minimal set of dependencies for what we want to do.
