### ISSUE TITLE
Allow skip predict_fn setup in Explainer init

### ISSUE THREAD

**Issue by cliveseldon** [SeldonIO/alibi#133]
For AnchorImage the model needs to be running at the time of the explainer creation as the predict_fn is called:

https://github.com/SeldonIO/alibi/blob/bedbd4704e5299401805da33bcdc5fe70220b275/alibi/explainers/anchor_image.py#L46-L49

For use in kfserving it would be preferred if this was skipped as the predict_fn will be replaced later at inference time. Could we have a flag to skip this and rerun on first `explain` call if it was skipped? 

This will allow an explainer to be saved without needing access to the model and better separate the explainer from the model.

This could be considered for all explainers?

Atr present it also means when we replace the predict_fn at inference time we need to rerun the above code which is copied into the kfserving library. This is error prone and a duplication of code.

**Comment by arnaudvl** [comment]
While this can be done for Anchor models, it will be harder for e.g. counterfactual methods as the predict function or model is used when setting up the TF graph and during the fit stage.

**Comment by jklaise** [comment]
We can have a `set_predict_fn` doing shape inference etc. for all explainers which can be called at `init` time when a local model is available and called at first `explain` time if it needs to be overwritten by a live prediction endpoint.

**Comment by jklaise** [comment]
Closing as #359 addresses this.
