### ISSUE TITLE
Could the CEM explanations contain extra colours?

### ISSUE THREAD

**Issue by MarcoGorelli** [SeldonIO/alibi#143]
The [CEM paper](https://arxiv.org/pdf/1802.07623.pdf) shows an example image which is made very clear via the use of different colours (cyan for pertinent positive mode, pink for pertinent negative):
![Screenshot from 2019-09-17 19-13-13](https://user-images.githubusercontent.com/33491632/65067795-3da7ec80-d97f-11e9-9548-91faff4fd6b3.png)

On the other hand, the `cem_mnist` example from the alibi docs contains black-and-white images. I think this makes the pertinent negative example a little hard to understand, as it's not obvious which are the extra pixels which are minimally but critically absent. Could they be coloured in?

I can work on a PR if you're interested in this.

**Comment by arnaudvl** [comment]
Hi @MarcoGorelli, yes absolutely. A PR for it would be most welcome. We will also be integrating visualisation methods to display the output of the different explainers clearly later on.
