### ISSUE TITLE
Need data-type and explainer-type info in the explanation output 

### ISSUE THREAD

**Issue by SachinVarghese** [SeldonIO/alibi#153]
Is it a good idea for the explainer to have info about the explainer type and data type?

For example, dataType being "text" and explainer type being "anchor" and these two values to be present in the alibi response would be useful.

**Comment by jklaise** [comment]
This will be part of the new API (#113) in the metadata of the explainer and the explanation as well.

**Comment by jklaise** [comment]
Closed by #156
