### ISSUE TITLE
Visualization backend

### ISSUE THREAD

**Issue by jklaise** [SeldonIO/alibi#165]
We've started thinking about adding visualization to the outputs of explainer methods. One of the biggest decisions is the backend to use for this. Whilst `matplotlib` is standard, it is not portable outside the Python and more importantly does not define a grammar of graphics. A promising alternative is [vega-lite](https://vega.github.io/vega-lite) with the Python package [altair](https://altair-viz.github.io). There also seems to exist an integration with React: [react-vega](https://github.com/vega/react-vega) which would make it easier with frontend integration of other products. @SachinVarghese

**Comment by SachinVarghese** [comment]
The grammar for graphics spec from vega has great inbuilt features like selecting, panning, zooming, etc. Also, the interoperability perspective with python is a nice concept.  The only downside I see is that the js bit of the library is still relatively less tested in terms of usage in real applications and hence also little documentation. But I don't see that as a reason enough not to experiment or adapt this in our tools. @jklaise Do you have any initial thoughts on how we will be using this spec?

**Comment by jklaise** [comment]
That's interesting, I thought the JS side would've been more mature.

My thinking was that we could have visualization in Python using Altair, but because of the grammar we can also generate the visualization spec from within Alibi and send it back over to a React frontend for rendering there. The main appeal is interoperability and avoiding writing visualization twice (in Python and JS). Of course if we require very custom visualization this might not be enough.

I was going to test Altair for either the `AnchorTabular` visualization or when I get back to #152 .

**Comment by jklaise** [comment]
Closing as this is now beyond the scope of the library.
