### ISSUE TITLE
Working with dataframe

### ISSUE THREAD

**Issue by vahedq** [SeldonIO/alibi#185]
I am trying to use Alibi for a pipeline that starts with dataframes but uses `ColumnTransformer`.

`ColumnTransformer` converts data from dataframe to `np` arrays, and I get this error when trying to use `alibi` like this :
`explainer = AnchorTabular(predict_fn, feature_names, categorical_names=category_map)`
and get this  error:
`ValueError: Specifying the columns using strings is only supported for pandas DataFrames`.

What should I pass as `feature_names` to this constructor to work?

**Comment by jklaise** [comment]
Can you provide a minimal example? `feature_names` should just be a list of strings, I suspect the issue is actually with using dataframes as the input to the model as currently the explainers expect numpy arrays.

**Comment by vahedq** [comment]
I was able to get this to work with numpy arrays as suggested. Please feel free to close the issue.

**Comment by arnaudvl** [comment]
Great!
