### ISSUE TITLE
[Question] Is it possible to save counterfactual explainers to a file?

### ISSUE THREAD

**Issue by sug4ndh** [SeldonIO/alibi#187]
Hi,

I was wondering if it is possible to save Counterfactual explainers to a file and then load them up at a later stage?

Thanks!

**Comment by arnaudvl** [comment]
There is currently no straightforward way to save/load a fitted Counterfactual explainer. We aim to migrate the counterfactuals to TensorFlow 2 in the near term and will add this functionality with the migration. What you can do however is save the attributes (e.g. with pickle) that are used when the explainer is initialised or are computed when invoking the `fit` function and assign those values to an initialised counterfactual explainer later on to create a loaded explainer. 

For **CounterFactualProto** The relevant attributes depend on whether you use an encoder or the k-d trees for the prototypes.

Attributes when using encoder model:
* class_proto
* class_enc

When using k-d trees:
* kdtrees
* X_by_class

When you have categorical variables:
* d_abs
* cat_vars_ord
* d_abs_ragged
* feature_range if you set `update_feature_range=True` in the fit function

I don't think the vanilla **Counterfactual** method needs to fit any variables, so you would only need to save the variables to initialise the explainer.

**Comment by sug4ndh** [comment]
Thanks again @arnaudvl  for the awesome answer! :)
