### ISSUE TITLE
Issue with category mapper

### ISSUE THREAD

**Issue by ktroutman** [SeldonIO/alibi#213]
When passing a list of column names into the ```gen_category_map``` function from [utils.data.py](https://github.com/SeldonIO/alibi/blob/master/alibi/utils/data.py), I get a value error, for using a string on an iloc slicer.

Here is the relevant code.
```python
# create the map
    category_map = dict.fromkeys(categorical_columns)
    for col in categorical_columns:
        le = LabelEncoder()
        try:
            _ = le.fit_transform(data.iloc[:, col])
        except (AttributeError, IndexError):
            raise

        category_map[col] = list(le.classes_)

    return category_map
```

I'm not sure if ```categorical_columns``` is supposed mapped to an index location, but it seems like maybe you meant to use loc? Or if this isn't right, then maybe put into type hint for ```categorical_columns``` for guidance?

```python
# create the map
    category_map = dict.fromkeys(categorical_columns)
    for col in categorical_columns:
        le = LabelEncoder()
        try:
            _ = le.fit_transform(data.loc[:, col])
        except (AttributeError, IndexError):
            raise

        category_map[col] = list(le.classes_)

    return category_map
```

**Comment by jklaise** [comment]
Good catch, currently the implementation expects integer indices for the columns, so a type `List[int]` would be more appropriate. I'll open a PR to extend the functionality to pass a list of strings with column names.
