### ISSUE TITLE
Unified explainer API

### ISSUE THREAD

**Issue by jklaise** [SeldonIO/alibi#23]
We should settle on a unified API. Currently the thinking is that an explainer has to implement an `explain` method and optionally a `fit` method (for cases where there is computation/dependency on the training set). We could write this as an abstrast `BaseExplainer` from which every other explainer inherits. To support multiple inheritance, we could use mixin classes (c.f. `scikit-learn` `BaseEstimator`).

**Comment by jklaise** [comment]
See #113 for WIP

**Comment by arnaudvl** [comment]
#166

**Comment by jklaise** [comment]
Closed by #166 .
