### ISSUE TITLE
Failure to import with tensorflow 1.10.0

### ISSUE THREAD

**Issue by jimbudarz** [SeldonIO/alibi#230]
Hi, I installed alibi 0.4.0 with tensorflow 1.10.0 and am getting the following error when importing the package in python. According to setup.py, the only tensorflow version requirement is that tensorflow<2.0. 

```
import alibi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[hidden]/lib/python3.5/site-packages/alibi/__init__.py", line 1, in <module>
    from . import confidence, datasets, explainers, utils
  File "[hidden]/lib/python3.5/site-packages/alibi/explainers/__init__.py", line 8, in <module>
    from .cem import CEM
  File "[hidden]/lib/python3.5/site-packages/alibi/explainers/cem.py", line 10, in <module>
    from alibi.utils.tf import _check_keras_or_tf
  File "[hidden]/lib/python3.5/site-packages/alibi/utils/tf.py", line 11, in <module>
    Tuple[bool, bool, tf.compat.v1.Session]:
AttributeError: module 'tensorflow.compat' has no attribute 'v1'
```

Thanks so much for the help!

**Comment by jklaise** [comment]
Hi, whilst it's true that we specify a TF version of 1.x, in practice 1.10 is a very old release which we haven't tested against as it was already several releases old when we began the development of the library. I would suggest upgrading to 1.15 which is the latest 1.x release. In the near future we will be transitioning to TF 2.x support.

Also, bear in mind with the next release we will be dropping support for Python 3.5 as well.

**Comment by jimbudarz** [comment]
Thanks for the response. Unfortunately 1.15 is not permitted for me- perhaps the requirements can be adjusted to reflect the minimum version necessary. 

Is there a roadmap for TensorFlow 2.x support?

**Comment by arnaudvl** [comment]
Hi Jim, the [requirements](https://github.com/SeldonIO/alibi/blob/master/requirements/requirements.txt) show `tensorflow>=1.15.0,<2.0` but I see that the Dependencies section in the README does not specify this, we should adjust this.

Wrt TensorFlow 2.x, we are actively working to migrate the algorithms to be compatible with TF2. The Integrated Gradients method (#205 ) is TF2 compatible and the counterfactual methods are being migrated as well.

**Comment by jimbudarz** [comment]
Thanks Arnaud. I was also referring to the setup.py which only indicates tensorflow<2.0.

**Comment by jimbudarz** [comment]
Thanks. I guess I misunderstood the use of the setup.py file which only indicated tensorflow<2.0.

**Comment by jklaise** [comment]
The newest version is now running on tensorflow>=2.0.
