### ISSUE TITLE
Tensorflow 1.x in requirements

### ISSUE THREAD

**Issue by AndrewLouw** [SeldonIO/alibi#237]
When installing alibi my tensorflow 2.2 install got rolled back to 1.5.
Is it absolutely necessary to be using Tensorflow 1.x and not 2.2/ a more recent version? 
It's a concern when developing models using Tensorflow 2.2 and then loading them for analysis in 1.5, especially as in future I'll be moving to the ONNX format that 1.5 won't be able to load easily. 

cheers
A

**Comment by jklaise** [comment]
We're in the process of migrating the methods that are using TensorFlow to TF2.x. Additionally we're exploring ways of making the library more flexible by not requiring some of the heavy dependencies like TF unless you are interested in the methods that depend on it.

**Comment by AndrewLouw** [comment]
Great, thanks
