### ISSUE TITLE
Incorrect expected_value from alibi.explainers.TreeShap.explain function

### ISSUE THREAD

**Issue by shade307** [SeldonIO/alibi#253]
Expected_value of shap.TreeExplainer.expected_value not matching with the one provided from alibi.explainers.TreeShap.explain
Have used xgboost multiclass classification model for generating the shap values on a modified IRIS dataset.

**At stage** **explainer.fit()**
The shap.TreeExplainer returns a value (in my case [0.41060104 0.39954053 0.37059403]) as the “expected_value” which is directly assigned to “self.expected_value” inside fit function of alibi.explainers.TreeShap (_line number 1109 at https://github.com/SeldonIO/alibi/blob/master/alibi/explainers/shap_wrappers.py_)

**At Stage** **explainer.explain(df)**
The shap.TreeExplainer refreshes the expected value with the bias value of phi (which is [-0.100694835, 0.5807366, 0.700694] in my case). But in explain function of shap_wrappers.py (_line 1249 at https://github.com/SeldonIO/alibi/blob/master/alibi/explainers/shap_wrappers.py_) the value of expected_value is assigned with previously set value and not refreshed with the new calculated value of shap.TreeExplainer expected_value

**Comment by alexcoca** [comment]
Hi @shade307,

Good catch. I'll update the wrapper so that it returns the same expected value as the underlying explainer. Thank you for reporting it.

**Comment by alexcoca** [comment]
Hi @shade307,

Thanks for raising this, we've put a temporary fix in. Just so we understand better your setup, you're calling `fit` with no arguments, right? What is your model class name?

**Comment by shade307** [comment]
Yes @alexcoca , I am using fit without any arguments.
Am using xgboostClassifier (**XGBClassifier**) model for explanation. Strictly speaking its **"xgboost.core.Booster"**, on iris dataset.

Treeshap explainer used is as follows:
_from alibi.explainers import TreeShap_
_explainer = TreeShap(predictor=xgbm, feature_names= ['sepal_length','sepal_width','petal_length','petal_width'], model_output="raw", task='classification')
explainer.fit()
explainer.explain(df)_
Here df is pandas dataframe with values -> [[4.7,2.6,1.1,0.3]]
