### ISSUE TITLE
Link in Example (Integrated gradients for MNIST) not working

### ISSUE THREAD

**Issue by CrazyChristoph** [SeldonIO/alibi#256]
The first link in the [Integrated gradients for MNIST example](https://docs.seldon.io/projects/alibi/en/latest/examples/integrated_gradients_mnist.html) is not working properly, it should lead to a more detailed description of the method but it always shows that this **page does not exist**.

The link leads to: [https://docs.seldon.io/projects/alibi/en/latest/doc/source/methods/IntegratedGradients.ipynb](https://docs.seldon.io/projects/alibi/en/latest/doc/source/methods/IntegratedGradients.ipynb) 
but it should lead to: [https://docs.seldon.io/projects/alibi/en/latest/methods/IntegratedGradients.html](https://docs.seldon.io/projects/alibi/en/latest/methods/IntegratedGradients.html) 

In the notebook (from which the page is created) the link works and leads to the notebook with a more detailed description of the method.

**Comment by jklaise** [comment]
Thanks for flagging!

**Comment by CrazyChristoph** [comment]
@jklaise down the documentation there is the same thing again in the section **Calculate integrated gradients**.
Thanks for the fast fix

**Comment by jklaise** [comment]
Ah I see, I'll fix that too, thanks!
