### ISSUE TITLE
Regression support

### ISSUE THREAD

**Issue by michael135** [SeldonIO/alibi#264]
Is it planned to support Regression (In addition to classification)?

**Comment by jklaise** [comment]
Hi, it depends on the method, I assume you've seen the comparison table on the readme? Some methods naturally support regression tasks out of the box (ALE, IG, KernelSHAP and TreeSHAP), others could be extended to support regression (Counterfactuals) and for some other it is unclear how to extend them to support regression (Anchors). Are there methods that you are particularly interested in?
