### ISSUE TITLE
TypeError when passing preprocessing pipeline + estimator to KernelShap

### ISSUE THREAD

**Issue by ktroutman** [SeldonIO/alibi#265]
Following the example in [this notebook](https://github.com/SeldonIO/alibi/blob/524d786c81735ed90da2d2c68851c1145fa1b595/examples/kernel_shap_adult_categorical_preproc.ipynb), I get the following TypeError: 

_TypeError: ufunc 'isinf' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''_

I can recreate this exact same error if I try to use the preprocessing pipeline with the SHAP

```python 
pred_fcn = lambda x: estimator.predict_proba(preprocess_pipeline.transform(x))[:,1]
explainer_shap = shap.KernelExplainer(pred_fcn,raw_data.iloc[0:100,:])
```
I get this to work if I break uf the pred_fcn function by preprocessing the data and then just running predict_proba on the transformed data. But obviously I'd like to be able to do as you seem to have done in the notebook and go from raw data to explaination with a single function call.

This seems to be an [issue](https://github.com/slundberg/shap/issues/1058) that others have had as I've seen questions about this on stackoverflow, so I was wondering if this was something you encountered / addressed and that I have missed somehow.

alibi==0.4.0
numpy==1.18.1
shap==0.35.0

**Comment by jklaise** [comment]
Just to make sure, the notebook example doesn't work exactly as written or is this an error with some other dataset?

**Comment by ktroutman** [comment]
Hi @jklaise , apologies for the late response. I ran this again from the original repo and in clean venv and it works fine. Must be some conflict on my side. Ok to close.
