### ISSUE TITLE
Cannot concatenate gradients in IntegratedGradients.explain

### ISSUE THREAD

**Issue by Realvincentyuan** [SeldonIO/alibi#268]
In the example of [integrated_gradients_imdb.ipynb](https://github.com/SeldonIO/alibi/blob/0104a7733a980bc44c0bd63d68a1f59c053b3eee/examples/integrated_gradients_imdb.ipynb), the function of 

`
explanation = ig.explain(x_test_sample,
                         baselines=None,
                         target=predictions)
`
Threw the error when I tried to replicate the results.

### error: 
![image](https://user-images.githubusercontent.com/26101303/87895405-ef201e80-ca77-11ea-8e16-9a7ef73566ec.png)

I did not modify the model and it exactly followed the example but met this error. Please take a look.

**Comment by gipster** [comment]
Hi. 
I cannot recreate the error. Did you run the notebook without any modification? 
It seems like the variable `shape` is of type TensorShape when it should be of type `tuple` in your error. 
What version of tensorflow are you running?

**Comment by Realvincentyuan** [comment]
> Hi. 
> 
> I cannot recreate the error. Did you run the notebook without any modification? 
> 
> It seems like the variable `shape` is of type TensorShape when it should be of type `tuple` in your error. 
> 
> What version of tensorflow are you running?

Hi,

I am using TF 1.14. The predictions is a ndarray in my side so that's why It is strange since the source says it can take ndarray. and I did not do any modification on the sample code.

**Comment by gipster** [comment]
Hi. I manage to reproduce the error with tensorflow 1.14. The problem is with the variable `shape` , which is the shape of the grads tensor. In TF 1.14 is returned as type `TensorShape`, while in later versions is returned as type `tuple`. 
I will create a patch to make it compatible with older version of tensorflow. It works with TF 1.15.3.

**Comment by Realvincentyuan** [comment]
> Hi. I managed to reproduce the error with tensorflow 1.14. The problem is with the variable `shape` , which is the shape of the grads tensor. In TF 1.14 is returned as type `TensorShape`, while in later versions is returned as type `tuple`. 
> 
> I will create a patch to make it compatible with older version of tensorflow. It works with TF 1.15.3.

Thank you for the quick turnaround! When are you going to release it? So that I can update the package to have this new feature. Otherwise I have to tweak a lot of code.

**Comment by Realvincentyuan** [comment]
> @Realvincentyuan is it possible for you to use the development version (`pip install git+https://github.com/SeldonIO/alibi.git `) directly?

yup, I chose to clone the repo and import it. And it works, it's great work, very intuitive to users. Thank you!
