### ISSUE TITLE
Conflicting dependencies with alibi-detect

### ISSUE THREAD

**Issue by iionez** [SeldonIO/alibi#274]
Wondering if there was a workaround to use `alibi` (requires tensorflow>=1.15.0,<2.0) and `alibi-detect` (requires tensorflow>=2.0.0) in the same environment?

**Comment by jklaise** [comment]
We're currently working on upgrading alibi to work with TF>=2.0 (see #260) which should hopefully be ready soon. If you are not using the explainers that actually rely on TF1.x (i.e. `CounterFactual`, `CEM` and `CFProto`), then you should be able to import import both packages in an environment where TF2.x is installed. The tricky part would be actually installing both packages... As a workaround I would suggest cloning the `alibi` repo, editing `setup.py` to remove the `<2.0` part of the tensorflow requirement and then installing the package from source `pip install -e .`.

**Comment by jklaise** [comment]
This has now been resolved as from version `0.5.2` we use TF>=2.0.
