### ISSUE TITLE
KeyError: "[E018] Can't retrieve string for hash while running movie sentiment example

### ISSUE THREAD

**Issue by devchaitu18** [SeldonIO/alibi#275]
While running movie sentiment example I am getting the following error while running the code `explainer = AnchorText(nlp, predict_fn):`

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-12-184c1e0a132f> in <module>()
----> 1 explainer = AnchorText(nlp, predict_fn)

2 frames
/usr/local/lib/python3.6/dist-packages/alibi/explainers/anchor_text.py in <listcomp>(.0)
     43         self.w_prob = w_prob
     44         # list with spaCy lexemes in vocabulary
---> 45         self.to_check = [self.nlp.vocab[w] for w in self.nlp.vocab.vectors if self.nlp.vocab[w].prob >= self.w_prob]
     46         self.n_similar = n_similar
     47 

vocab.pyx in spacy.vocab.Vocab.__getitem__()

lexeme.pyx in spacy.lexeme.Lexeme.__init__()

vocab.pyx in spacy.vocab.Vocab.get_by_orth()

strings.pyx in spacy.strings.StringStore.__getitem__()

KeyError: "[E018] Can't retrieve string for hash '11580349482641876976'. This usually refers to an issue with the `Vocab` or `StringStore`."

**Comment by jklaise** [comment]
What version of spacy have you got installed?

**Comment by devchaitu18** [comment]
alibi-0.5.2.dev0
spacy[lookups] in /usr/local/lib/python3.6/dist-packages (from alibi==0.5.2.dev0) (2.2.4)

**Comment by jklaise** [comment]
I can reproduce this with spacy 2.2.4. The issue relates to differences in how spacy handles word vectors in older versions, in particular this line https://github.com/SeldonIO/alibi/blob/19a4ba97228cc514bab31c5ac802c0bae2db1c65/alibi/explainers/anchor_text.py#L45 results in the error for spacy 2.2.4 whilst it is correct for spacy>=2.3.0. I will think how we can handle both cases gracefully, in the meantime I would recommend upgrading to spacy>=2.3.0.

**Comment by adrianeboyd** [comment]
A workaround would be:

```
self.to_check = [self.nlp.vocab[w] for w in self.nlp.vocab.vectors if int(w) in self.nlp.vocab.strings and self.nlp.vocab[w].prob >= self.w_prob]
```

The keys in `nlp.vocab.vectors` are supposed to all be `int`, but in some v2.2 `md` models they're accidentally `numpy.uint64`.

**Comment by jklaise** [comment]
@adrianeboyd thanks for the workaround. @devchaitu18 I'll put this in the master shortly.
