### ISSUE TITLE
alibi conda package

### ISSUE THREAD

**Issue by shoaibkhanz** [SeldonIO/alibi#301]
Are there any plans to publish the package to conda anytime soon?
The reason I ask this is because at work we are blocked using pypi for some reason which I have no clue of.

**Comment by jklaise** [comment]
@shoaibkhanz good point, we can certainly look into it.

**Comment by jklaise** [comment]
I've checked that due to us using `prettyprinter` which is not on conda itself we would have to either get rid of this dependency or provide a conda recipe for `prettyprinter` as well. Will investigate.

**Comment by jklaise** [comment]
Would be nice to have but need to weight the pros of being in the conda ecosystem vs the cons of maintaining the conda recipe. Also my previous attempt was unsuccessful due to `tensorflow` issues which I wasn't able to resolve, see https://github.com/conda-forge/staged-recipes/pull/12953 .

**Comment by sugatoray** [comment]
@jklaise Is it necessary to leave this issue `open`? Could it be closed now that `alibi` is available on conda-forge?

**Comment by ascillitoe** [comment]
Good spot @sugatoray, I shall close this now. Thanks!
