### ISSUE TITLE
Counterfactual instance is different from prediction

### ISSUE THREAD

**Issue by rmazzine** [SeldonIO/alibi#323]
Hello,

first of all, great algorithm and work, congratulations!

I think there's a small bug on the code.

Consider a mixed (categorical and numerical) dataset.

In these lines:

https://github.com/SeldonIO/alibi/blob/22509a948a0569954b81681826cef314202bf4e7/alibi/explainers/cfproto.py#L570-L578

you predict the probability of the perturbed (CF candidates) instances.

However, in certain conditions (the first perturbation generates a CF), a bug (might) happen. As you are assigning the prediction `self.pred_proba` from the perturbed instances `self.adv_cat` or `self.adv_cat_s` **and not from the instance `self.adv`**, the following occurs:

* `self.adv_cat` or `self.adv_cat_s` have a valid counterfactual that generates a `self.pred_proba` result that indicates a CF.
* `self.adv` is not equal to `self.adv_cat` or `self.adv_cat_s`
* The following conditional will be true:

https://github.com/SeldonIO/alibi/blob/22509a948a0569954b81681826cef314202bf4e7/alibi/explainers/cfproto.py#L1220-L1221

However, the prediction results are from  `self.adv_cat` or `self.adv_cat_s`, however `adv_idx` is from `self.adv`. And `self.adv` is not a counterfactual.

This is a weird bug, as it does not happen if the first prediction is not a CF (maybe the `self.adv` update is not well connected!)

**Comment by jklaise** [comment]
Hi, thanks for raising the concern.

I'm not sure there is an issue as `self.adv` and `self.adv_cat` represent the same instance, that is `self.adv_cat` is the format of the instance that the original model can take (contains one-hot or ordinally encoded categorical vairables) whilst `self.adv` is the transformed instance for which all categorical variables have been encoded in numerical space. `self.adv` is ultimately the variable that is optimized, but we need to perform the reverse mapping to get `self.adv_cat` to feed it into the model to get the prediction probabilities.

It's possible that I've misunderstood something, from what you've mentioned wrt to the first prediction, do you think there is some synchronization issue between `self.adv` and `self.adv_cat` as they're always supposed to represent the same instance?
