### ISSUE TITLE
Unclear coverage calculation in AnchorTabular

### ISSUE THREAD

**Issue by alexHeu** [SeldonIO/alibi#328]
Hi,

i applied the AnchorTabular module to the standard Titanic dataset and got weird coverage values.

Here is an example Anchor result for a non-surviving instance:
![image](https://user-images.githubusercontent.com/8157458/102096284-d0eefc80-3e24-11eb-844f-8a49346b21ce.png)
The Anchor appears to make sense but coverage seems high. As far as I understood, coverage gives the fraction of other sampled instances that this Anchor can be applied to. Since the titanic dataset is small, I guess this fraction can be seen as the fraction of the overall data.

Second example for a surving instance:
![image](https://user-images.githubusercontent.com/8157458/102096703-4ce94480-3e25-11eb-97b7-bf0d77085198.png)
Here, I notices that the coverage of example 1 and 2 sum up to 1 so I checked the dataset distribution of gender and found that the dataset consists of 78% males and 22% females. 

Am I missing something in the definition of coverage or is the coverage calculation only considering the first rule of the anchor?

Thanks for any insight that you can provide.

**Comment by jklaise** [comment]
Hi, thanks for raising the issue. This is indeed strange, the coverage of an anchor should be taking into account all rules so it's possible this is an implementation bug, we will look into this.

**Comment by jklaise** [comment]
@alexHeu I can confirm that I've reproduced this and it looks like it is a bug in how we track the coverage. I will investigate further and submit a fix.
