### ISSUE TITLE
Error When Deploying Explainer Alongside LightGBM Model

### ISSUE THREAD

**Issue by FarrandTom** [SeldonIO/alibi#332]
## Describe the bug

Cannot get an explanation from a LightGBM classification model, when deploying a SHAP Tree explainer. (The error output can be found under Model Details below.) 

The LightGBM can be deployed successfully on it's own (Seldon Deploy 0.8.2) and the prediction endpoint can be called. It is only when deploying the explainer that the deployment breaks. 

Also tried using Python 3.6.8 and the same error occurs. 

## To reproduce

1. Import alibi
2. Created treeshap explainer based on training data
3. Used dill to export the object
4. Put it on s3
5. Called the object from Seldon Deploy

## Expected behaviour

An explanation returned to the user. 

## Model Details 
* Images of your model: Attached is the `explainer.dill` and the list of packages within the environment. 
[ExplainerTicket.zip](https://github.com/SeldonIO/alibi/files/5764394/ExplainerTicket.zip)

* Logs of your model: 
```
[I 201214 14:07:58 __main__:134] Loading Alibi model
14/12/2020 14:07:58 [I 201214 14:07:58 font_manager:1423] Generating new fontManager, this may take some time...
14/12/2020 14:07:58 Traceback (most recent call last):
14/12/2020 14:07:58   File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
14/12/2020 14:07:58     "__main__", mod_spec)
14/12/2020 14:07:58   File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
14/12/2020 14:07:58     exec(code, run_globals)
14/12/2020 14:07:58   File "/opt/app-root/src/alibiexplainer/alibiexplainer/__main__.py", line 135, in <module>
14/12/2020 14:07:58     alibi_model = dill.load(f)
14/12/2020 14:07:58   File "/opt/app-root/lib/python3.6/site-packages/dill/_dill.py", line 270, in load
14/12/2020 14:07:58     return Unpickler(file, ignore=ignore, **kwds).load()
14/12/2020 14:07:58   File "/opt/app-root/lib/python3.6/site-packages/dill/_dill.py", line 473, in load
14/12/2020 14:07:58     obj = StockUnpickler.load(self)
14/12/2020 14:07:58   File "/opt/app-root/lib/python3.6/site-packages/dill/_dill.py", line 463, in find_class
14/12/2020 14:07:58     return StockUnpickler.find_class(self, module, name)
14/12/2020 14:07:58 ModuleNotFoundError: No module named 'lightgbm'
```

**Comment by jklaise** [comment]
Thanks for the heads-up Tom. I think this is something to do with pickling the `lightgbm` object as an attribute of the `alibi` object so something fails when trying to unpickle here https://github.com/SeldonIO/seldon-core/blob/f89aa4043d104351c897d072560f8e375810c8ae/components/alibi-explain-server/alibiexplainer/__main__.py#L48 .

Happy to investigate further, but is it possible to provide the `Enivronment.txt` file in the `requirements.txt` format so that `pip` can use it to recreate the environment?

Also cc'ing @cliveseldon as he wrote the server.

**Comment by jklaise** [comment]
Closing as this is now tracked on the SC repo: https://github.com/SeldonIO/seldon-core/issues/2812.
