### ISSUE TITLE
Shap 0.38.1 breaks imports

### ISSUE THREAD

**Issue by jklaise** [SeldonIO/alibi#333]
Most recent release breaks importing which affects us. Need to specify avoiding this shap version in `setup.py` and make a new release. https://github.com/slundberg/shap/pull/1749

**Comment by RafalSkolasinski** [comment]
It's not the first time that shap breaks stuff for us. Should we add pinned source code of tested version as submodule to avoid headaches?

**Comment by jklaise** [comment]
I think we will go ahead with avoiding bad versions manually and check via daily `cron` builds which should flag any new releases of packages which break our code.
