### ISSUE TITLE
Support One Hot Encoding for AnchorTabular Explainers

### ISSUE THREAD

**Issue by FarrandTom** [SeldonIO/alibi#336]
Currently the AnchorTabular Explainer does not support the use of OHE variables. AnchorTabular does support the use of categorical variables encoded ordinally, but does not support OHE. 

Given how common an encoding scheme OHE is, and the fact that ordinal/label encoding is not suitable in all cases (there are some ML libraries where you cannot specify that you have ordinally/label encoded variables such as XGBoost and so they are simply treated as continuous numerical features which can introduce correlations that are not present in the true data) it would be great to extend the AnchorTabular explainer to support this case.

**Comment by jklaise** [comment]
Implemented in #422.
