### ISSUE TITLE
Constraints in alibi CounterFactualProto?

### ISSUE THREAD

**Issue by bsmiguel** [SeldonIO/alibi#338]
Hello,

I'm using CounterFactualProto with a neural network model defined by Tensorflow. 

I would like to generate counterfactuals without permuting some features. This means that I don't want to change the value for a specific feature. I'm not sure if this is possible. 
I have tried to modify the feature_range for the specific feature with None or 0 values.. but I obtain the same result that using the min and max values..

Thanks in advance!

**Comment by bsmiguel** [comment]
just found a similar issue https://github.com/SeldonIO/alibi/issues/327

**Comment by jklaise** [comment]
@bsmiguel yes, this is on our radar, any progress updates will be posted on the issue you linked.
