### ISSUE TITLE
Documentation still refers to Explanation objects as dictionaries

### ISSUE THREAD

**Issue by jimbudarz** [SeldonIO/alibi#350]
Hi,
After last year's changes to Explanation objects, it appears that the documentation hasn't caught up with the code (and warning messages about referencing explainer objects as dictionaries.)

The following pages and docstrings still refer to the Explanation objects and refer to them as dictionaries:

https://docs.seldon.io/projects/alibi/en/stable/methods/Anchors.html?highlight=explanation%20dictionary#id4
https://docs.seldon.io/projects/alibi/en/stable/methods/Anchors.html?highlight=explanation%20dictionary#id7
https://docs.seldon.io/projects/alibi/en/stable/methods/Anchors.html?highlight=explanation%20dictionary#Explanation
https://docs.seldon.io/projects/alibi/en/stable/methods/CEM.html?highlight=explanation%20dictionary#Explanation
https://docs.seldon.io/projects/alibi/en/stable/methods/CF.html?highlight=explanation%20dictionary#Explanation
https://docs.seldon.io/projects/alibi/en/stable/api/alibi.explainers.anchor_tabular.html?highlight=explanation%20dictionary#alibi.explainers.anchor_tabular.AnchorTabular.add_names_to_exp
https://docs.seldon.io/projects/alibi/en/stable/_modules/alibi/explainers/anchor_image.html?highlight=explanation%20dictionary#
https://docs.seldon.io/projects/alibi/en/stable/api/alibi.explainers.html?highlight=explanation%20dictionary#alibi.explainers.AnchorTabular.add_names_to_exp
https://docs.seldon.io/projects/alibi/en/stable/_modules/alibi/explainers/anchor_tabular.html?highlight=explanation%20dictionary#
https://docs.seldon.io/projects/alibi/en/stable/api/alibi.explainers.anchor_explanation.html?highlight=explanation%20dictionary#alibi.explainers.anchor_explanation.AnchorExplanation.__init__
https://docs.seldon.io/projects/alibi/en/stable/_modules/alibi/explainers/anchor_text.html?highlight=explanation%20dictionary#
https://docs.seldon.io/projects/alibi/en/stable/_modules/alibi/explainers/counterfactual.html?highlight=explanation%20dictionary#
https://docs.seldon.io/projects/alibi/en/stable/_modules/alibi/explainers/shap_wrappers.html?highlight=explanation%20dictionary#

**Comment by jklaise** [comment]
Nice catch! I will update these before the next release.
