### ISSUE TITLE
The kernel appears to have died. It will restart automatically.

### ISSUE THREAD

**Issue by oleg-savko** [SeldonIO/alibi#355]
When I create a new fresh conda env to test alibi library in JupyterLab (3.0.8)/Notebook. I instantly got following error when try to import alibi :

`import alibi`

`The kernel for example.ipynb appears to have died. It will restart automatically.`

Create new env:
```
conda create -n seldon python=3.8
conda activate seldon
pip install alibi
```

Try on new macbook air m1 in emulation mode (any another library work without problem).

_(the same situation with alibi-detect)_

What was can be the problem?

**udp:** if try import in console throw exception `illegal hardware instruction  python` :
```
(seldon) alehsauko@MacBook-Air ~ % python
Python 3.8.5 (default, Sep  4 2020, 02:22:02) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import alibi
zsh: illegal hardware instruction  python
```

**Comment by jklaise** [comment]
@oleg-savko it kind of looks to me that tensorflow isn't supported for apple M1 chips: https://github.com/tensorflow/tensorflow/issues/44999 . I'm not sure whether the x86 emulation mode should or should not work...

**Comment by oleg-savko** [comment]
> @oleg-savko it kind of looks to me that tensorflow isn't supported for apple M1 chips: [tensorflow/tensorflow#44999](https://github.com/tensorflow/tensorflow/issues/44999) . I'm not sure whether the x86 emulation mode should or should not work...

yes this problem with tensorflow deps, seems like need:
1. to compile from source to x86 https://github.com/tensorflow/tensorflow/issues/46044
2. or install TensorFlow-macOS version in native arm (but chance that all would be work on native arm seems not big... :( )

**Comment by rogerioluizsi** [comment]
I find the same on Linux Ubuntu. I open another issue on  #379

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic

Architecture:   x86_64
