### ISSUE TITLE
AttributeError: Layer my_model_2 is not connected, no input to return.

### ISSUE THREAD

**Issue by loukasilias** [SeldonIO/alibi#360]
I have implemented a Keras model by subclassing keras models. This model receives as input two texts and the output is a binary classification of the pair of inputs.
In this model, I am using BERT from huggingface and a custom layer.

```
n_steps = 100
method = "gausslegendre"
internal_batch_size = 768
nb_samples = 10
ig  = IntegratedGradients(model,
                          layer=model.bert_model,
                          n_steps=n_steps,
                          method=method,
                          internal_batch_size=internal_batch_size)
```

I am getting the following error: `AttributeError: Layer my_model_2 is not connected, no input to return.`

Any idea how to solve it? Thanks in advance.

**Comment by gipster** [comment]
Hey,

In your custom model, is `model.bert_model` the output layer of the pretrained bert model? Do you use your custom layer as a input? Thanks

**Comment by loukasilias** [comment]
Hi,
The model.bert_model gets the input. The output of this model, i.e., output['last_hidden_state'] is fed to the custom layer and then after some dense layers, I am getting the final output.

```
output_sentence_1 = self.bert_model(input_ids = inputs[0], attention_mask = inputs[2])
output_sentence_2 = self.bert_model(input_ids = inputs[1], attention_mask = inputs[3])
custom_layer_output = self.custom_layer([output_sentence_1['last_hidden_state'],output_sentence_2['last_hidden_state']])
```

**Comment by jklaise** [comment]
@loukasilias is it possible to provide a minimal example for which the error persists? Or what the full structure of your model looks like? Also, what is the referenced `my_model_2` in the error message?

**Comment by loukasilias** [comment]
```
class MyModel(tf.keras.Model):
    
    def __init__(self, flag):
        
        super(MyModel,self).__init__()
        self.bert_model = TFBertModel.from_pretrained("bert-base-uncased")
        self.bert_model.trainable = flag
        self.layer_4 = Dense(units = 1, activation = 'sigmoid')
        self.custom_layer = CustomLayer() #class CustomLayer(tf.keras.layers.Layer):

    def call(self,inputs):
        output_sentence_1 = self.bert_model(input_ids = inputs[0], attention_mask = inputs[2])
        output_sentence_2 = self.bert_model(input_ids = inputs[1], attention_mask = inputs[3])
        custom_layer_output = self.custom_layer([output_sentence_1['last_hidden_state'],output_sentence_2['last_hidden_state']])
        output = self.layer_4(custom_layer_output)

        return output
```
where the input is two sentences. I am training & evaluating the model:

```
model = MyModel(flag = False)

model.compile(optimizer=tf.keras.optimizers.SGD(learning_rate = 0.001),loss="binary_crossentropy",metrics=["acc",tf.keras.metrics.Recall(), tf.keras.metrics.Precision(),tf.keras.metrics.AUC(),
                                                                                       tf.keras.metrics.TrueNegatives(),tf.keras.metrics.FalsePositives()])
    
train_data = BertGenerator(X_train,y_train,batch_size=16)
eval_data = BertGenerator(X_eval,y_eval,batch_size = 16)
history = model.fit(train_data, epochs=50, verbose = 1, class_weight = class_weight_function(y_train),validation_data=eval_data,callbacks = [tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=10),
                                                                                                                                             tf.keras.callbacks.ReduceLROnPlateau(monitor='val_loss', mode = 'min',
                                                                                                                                             factor=0.1, patience=3)])
```

I am getting the following error with Integrated Gradients:

![error](https://user-images.githubusercontent.com/66082450/110332762-6fa48700-8029-11eb-80c3-8265ab8e3cf7.png)

**Comment by jklaise** [comment]
@loukasilias what is the type of `model.input` ?

**Comment by loukasilias** [comment]
The inputs to the model are the input_ids & attention_mask from huggingface (transformers). Type: <class 'numpy.ndarray'>

Train_data, eval_data --> Generators (<class '__main__.BertGenerator'>)

**Comment by jklaise** [comment]
Can you check if the problem persists if you remove the custom layer (i.e. you could set the output to be a concatenation of the two output sentences from `bert_model`) ?

Is `BertGenerator` part of the `transformers` library? We would need to reproduce your example to understand what's going on.

**Comment by gipster** [comment]
I manage to reproduce the error. 
```from transformers import TFBertModel
model =TFBertModel.from_pretrained("bert-base-uncased")

model.input
```
The problem arises from the input layer of the bert model. 
![Screenshot from 2021-03-08 15-47-34](https://user-images.githubusercontent.com/22886570/110337362-256dd680-8026-11eb-901a-f74500e98f60.jpg)

**Comment by loukasilias** [comment]
Is there any way of how to solve it?
For example, if I have the output of the BERT model, could I find which tokens/words have the greatest contribution for the final output?

**Comment by gipster** [comment]
The problem seems to be related specifically to the BERT model inputs. At the moment I'm not sure how to solve it. I think it's best to keep this issue open for further investigation
