### ISSUE TITLE
Image-net API is no longer available

### ISSUE THREAD

**Issue by theofpa** [SeldonIO/alibi#363]
Image-net [announced today](http://www.image-net.org/update-mar-11-2021.php) that their API for downloading the dataset is no longer available.

Alibi uses this API in [fetch_imagenet()](https://github.com/SeldonIO/alibi/blob/76e6192b6d78848dd47c11ba6f6348ca94c424c6/alibi/datasets.py#L95) to get the urls of the images for tests.

We're also using this in kfserving tests and just detected it in kubeflow/kfserving#1328

**Comment by jklaise** [comment]
@theofpa thank's for the heads up. I don't think there are/will be any publicly available APIs, so the best thing may be to include a handful of images in `alibi` for examples and tests.

**Comment by theofpa** [comment]
Yes, it makes sense. For kfserving I downloaded the urls of imagenet from dothub and most of them are down anyway. See [alibi's test here](https://github.com/kubeflow/kfserving/blob/master/python/alibiexplainer/tests/test_anchor_images.py).
