### ISSUE TITLE
Support native categorical features (without encoding) for AnchorTabular Explainers

### ISSUE THREAD

**Issue by oleg-savko** [SeldonIO/alibi#364]
Some algorithm like `Catboost` can use raw categorical features without manual encoding them. 

Seems like alibi  not support them now :(

**Comment by jklaise** [comment]
Thanks for opening the issue. Alibi currently works on models that take numpy arrays which require all entries to be of the same type (e.g. `int` or `float`). Allowing arbitrary strings would encode all columns (even numerical ones!) as strings which would be undesirable, therefore we require the categorical variables to be identified with integers.

We may extend the types of data handled by the alibi explainers in the future (e.g. working on `pandas` dataframes) but this is not an immediate priority as there are several potential complications with this.

In the meantime, one can support almost arbitrary input types by writing a small wrapper function that takes in `numpy` arrays in the format expected by `alibi`, transforms them in the format expected by your model and then define the predictor function to be this new wrapper function, e.g. see https://github.com/SeldonIO/alibi/issues/296#issuecomment-690137482 for an example on how to support models which take pytorch tensors as input.

**Comment by jklaise** [comment]
Closing as categorical variables are supported via both label/ordinal encoding and one-hot encoding as part of numpy array expected input to the model. For other types of inputs we can write some guidelines how to write custom wrappers for supporting models taking other data types.
