### ISSUE TITLE
AnchorText returns empty Anchor with Precision: 1.00

### ISSUE THREAD

**Issue by skocbek** [SeldonIO/alibi#381]
Hi, I have trained a model on a text dataset and applied the AnchorText explainer on the model. As a result I often get back an explanation with an empty Anchor and Precision: 1.00. Is this expected behavior? If yes, how do you explain it? Thanks.

**Comment by jklaise** [comment]
This can happen, the empty anchor can be returned when there is basically no restriction on the features to generate the same prediction. One way this can happen is because the training set may be unbalanced so during the sampling the algorithm mostly encounters instances of the same class which could then lead to an empty anchor.

**Comment by skocbek** [comment]
Thank you. My two classes are more or less equally balanced and I've tried to produce explanations on several different texts, some of them exactly the same as the ones in the training data and I still get an empty anchor. Actually, so far, I have not managed to input a text that would produce a non-empty anchor. I have around 50k training examples. Is this still somehow normal behavior?

**Comment by jklaise** [comment]
How many classes are there? Are you seeing this behaviour just for a particular class or across different classes?

**Comment by skocbek** [comment]
There are two classes and this behavior shows for both classes.

**Comment by jklaise** [comment]
What is the class balance?

**Comment by skocbek** [comment]
The classes are more or less well balanced.

  23490 0
  21417 1

**Comment by jklaise** [comment]
This has been addressed by the FAQ section: https://docs.seldon.io/projects/alibi/en/latest/overview/faq.html#why-is-my-anchor-explanation-empty-tabular-or-text-data-or-black-image-data
