### ISSUE TITLE
TensorFlow get_session deprecation

### ISSUE THREAD

**Issue by jimbudarz** [SeldonIO/alibi#388]
Hi, I've been seeing a warning message when running cfproto:

`WARNING:tensorflow:From <venv>/lib/python3.7/site-packages/alibi/utils/tf.py:26: The name tf.keras.backend.get_session is deprecated. Please use tf.compat.v1.keras.backend.get_session instead.`

I believe it has to do with TF2.0 compatibility and this `get_session` method being from TF1. 
Can it be resolved by just replacing all instances of `tf.keras.backend.get_session` with `tf.compat.v1.keras.backend.get_session`?

**Comment by jklaise** [comment]
Good catch, I think indeed it should be enough to switch to the `compat.v1` package.

**Comment by jimbudarz** [comment]
Great- I'll submit a PR once I can get a testing environment up and running for the tests.

**Comment by jklaise** [comment]
Closed via #390 .
