### ISSUE TITLE
Integrated Gradients for Regression 

### ISSUE THREAD

**Issue by senjed** [SeldonIO/alibi#400]
I am using the IG method for regression. I was wondering how can I interpret attribution values? Which of the following is correct?

(i) negative attribution score is associated with lower feature importance while a positive attribution score is associated with higher importance. 

(ii) We should consider the magnitude of the attributions and not the signs. A higher magnitude means more importance. If the sign is negative, it means the feature is correlated with lower final scores while a positive sign means it is correlated with a higher final score.

**Comment by jklaise** [comment]
Both sign and magnitude are important in interpreting the attribution values. An attribution value close to zero mean that the feature value is largely irrelevant for the prediction value observed whilst positive/negative attribution values mean that the feature value is positively/negatively correlated to the prediction value observed. The magnitude also gives the strength of the correlation.

This can be seen very clearly in the [IMDB example](https://docs.seldon.io/projects/alibi/en/latest/examples/integrated_gradients_imdb.html#Visualize-attributions): the prediction was "positive sentiment" and the highest magnitude positive attributions are for words such as "wonderuflly", "fascinating" etc. whilst the highest negative attributions are for words like "unfortunately", "bizzare" which, as one would expect, should correlate negatively with a "positive sentiment" prediction.

**Comment by senjed** [comment]
Thanks for the clarification. I played around with the IMDB example. It seems like, positive attribution means correlation with the predicted class (whether it is negative or positive prediction). But this is a classification problem with the binary output.  I was wondering if we have a scalar output (e.g. sentiment score between 1-5) how can we interpret the attributions? For example, given that the predicted sentiment value is 2. some words may get a high positive attribution like (e.g. +4 ) and some words may get a large negative attribution (e.g. -4). Can we conclude that they are equally important cause both have large and have similar magnitudes? (in a way treating them like coefficient in logistic regression)

**Comment by jklaise** [comment]
@senjed the positive scores will be correlated with the target that you're explaining, if you're explaining the predicted class, then positive attribution scores will be correlated with both positive and negative predictions. On the scalar output example I agree that we can conclude that attributions of similar magnitude regardless of sign would have similar importance, this is justified by the additive property of IG attributions (summing up all attributions is equal to the difference of the predictions on the instance and the baseline).

I recommend also reading section 3.1 of this paper which discusses the difficulty in interpreting attributions in the context of images: https://arxiv.org/abs/1706.03825
