### ISSUE TITLE
Remove spaCy dependency in AnchorText for UNK sampling

### ISSUE THREAD

**Issue by arnaudvl** [SeldonIO/alibi#41]

**Comment by jklaise** [comment]
@arnaudvl is this still relevant?

**Comment by Lauren-Archer** [comment]
yes

**Comment by arnaudvl** [comment]
I agree that UNK sampling is not the preferred option for good explanations. One reason is that by using UNK tokens for words outside of the proposed anchors, the text is highly likely to be far out of the model's distribution and therefore less reliable. E.g. the sentence "I am going to the cinema" could become "UNK UNK UNK to UNK cinema" instead of a perturbed sentence where the similarity scores between words from a spacy model are used, therefore keeping more of the context. Throwing a warning for the UNK default could indeed be a solution.

**Comment by jklaise** [comment]
This is actually not straightforward as even if we use UNK sampling, `spacy` is used internally to tokenize any text passed to `explain`. We don't have plans to use different tokenizers so I feel like this issue will have to be closed. @arnaudvl .

**Comment by jklaise** [comment]
Closing this as `spacy` is used internally for tokenizing text for both `unknown_sampling` and `similarity_sampling`.
