### ISSUE TITLE
TensorFlow 2.5 support

### ISSUE THREAD

**Issue by tgaddair** [SeldonIO/alibi#416]
TensorFlow recently released [v2.5.0](https://pypi.org/project/tensorflow/2.5.0/), but Alibi has TensorFlow [pinned to <2.5.0](https://github.com/SeldonIO/alibi/blob/master/setup.py#L40). 

Is there any reason to believe Alibi would not be compatible with the latest TensorFlow? Can this upper bound be removed?

**Comment by jklaise** [comment]
Originally there were conflicts due to this: https://github.com/SeldonIO/alibi/pull/411#issuecomment-841238917 . However, we have removed old Keras support so looks like the bound could be lifted. I will check again shortly.

**Comment by jklaise** [comment]
TF 2.5 is now supported on master and will be part of the next release.

**Comment by jklaise** [comment]
TF2.5 is now supported from `v0.6.0`.
