### ISSUE TITLE
Add notebooks showing pros/cons of different techniques

### ISSUE THREAD

**Issue by arnaudvl** [SeldonIO/alibi#42]
Highlight pros and cons for different explanation techniques by comparison using examples. Compare open source libraries (e.g. LIME, SHAP, PDP etc) with techniques in alibi and illustrate where for instance approaches which do not respect the data distribution through perturbations or where local linearizations generate misleading explanations.

**Comment by jklaise** [comment]
This has been partially addressed via #510. A rigorous evaluation of explainability methods may be better suited for a research project; if this happens then Alibi may get some additional documentation.
