### ISSUE TITLE
 For RNN models?

### ISSUE THREAD

**Issue by nyou70** [SeldonIO/alibi#433]
Hello 
Is it possible to use the alibi package for RNN models?
which type of explainer should I use for that?

**Comment by jklaise** [comment]
Hi, the algorithms mostly depend on the type of framework and modelling task rather than the specific architecture, e.g. check here: https://github.com/SeldonIO/alibi#model-explanations . This should also inform you which approaches would be more relevant depending on your use case.

**Comment by nooshin70** [comment]
I have a GRU model for binary classification, and my data is sequential tabular data. Also my code is in TF2. 
Any suggestion for explainer?

**Comment by jklaise** [comment]
Integrated Gradients is probably a good one to start with.

**Comment by nyou70** [comment]
Thank you so much for your response. Do you think I can also use counterfactual explainer?

**Comment by jklaise** [comment]
That should be possible too but not necessarily if you have categorical variables (e.g. `CounterFactualProto` supports categorical variables, but expects 2D inputs instead of 3D as would be the case for sequences of tabular data).
