### ISSUE TITLE
Rename counterfactual classes

### ISSUE THREAD

**Issue by jklaise** [SeldonIO/alibi#468]
With #457 merging soon, we want to standardize the naming of some of the explainer classes, i.e. `CounterFactual` --> `Counterfactual` and `CounterFactualProto` --> `CounterfactualProto`. This would of course be a breaking change, but we can deprecate the old names and issue a warning message that the old classes will be removed in an upcoming release.

**Comment by aniketzz** [comment]
just updating the alibi 0.6.0 to alibi 0.6.1 fix this issue.

**Comment by jklaise** [comment]
Ah this issue was for keeping track of #469 which is now merged, so closing this.
