### ISSUE TITLE
Replace Boston dataset in examples

### ISSUE THREAD

**Issue by jklaise** [SeldonIO/alibi#490]
The Boston dataset which we use in some examples has an ethical problem and should be replaced. Read more here: https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_boston.html#sklearn.datasets.load_boston

Impacted examples:
 - `cfproto_housing.ipynb`
 - `ale_regression_boston.ipynb`

The above link suggests some similar housing-related alternatives.

**Comment by Pranjalmishra30** [comment]
Hey, i would like to work on this issue. Could you assign this to me ?
There are 2 dataset-alternatives ( California and Ames), is there any preference for either of them. Also would i need to the change the documentation in each of these files.

**Comment by jklaise** [comment]
Thanks for your interest! You're right that this PR would need re-writing parts of the examples to talk about the new dataset.

The key thing for both examples is that they require a dataset with only numerical features (no categorical ones) which both datasets seem to satisfy. I would start with the California one as it's has fewer features.

**Comment by Pranjalmishra30** [comment]
Ok understood. Will get on this ASAP. Also out of curiosity, are you planning to accept contributions for hacktoberfest ?

**Comment by jklaise** [comment]
I'm not familiar with how Hacktoberfest works, are there any particular requirements other than what we already do?

**Comment by Pranjalmishra30** [comment]
You just need to add the topic [Hacktoberfest](https://github.com/topics/hacktoberfest) to the repository.
You can refer the following links for more details:
- https://hacktoberfest.digitalocean.com
- https://hacktoberfest.digitalocean.com/resources/maintainers

**Comment by jvasque** [comment]
I resolve that:

`import requests
import numpy as np
import pandas as pd

# Code to use the dataset from the source
data_url = "http://lib.stat.cmu.edu/datasets/boston"
sepa = "\\s+"
raw_df = pd.read_csv(data_url, sep=sepa, skiprows=22, header=None)  # Reads the data skipping the first 22 lines
data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])  # Combines the rows to form the data matrix
target = raw_df.values[1::2, 2]  # The target values are in the third column of odd rows

# Download the content of the file
response = requests.get(data_url)
lines = response.text.splitlines()

# Capture the first 22 lines as the description
descr = lines[:22]

# Capture the names of the variables from line 8 to line 21
feature_names = [line.split()[0] for line in lines[7:21]]

# Create a structure similar to the class to keep the same examples

# Define the BostonData class
class BostonData:
    def __init__(self, data, target, feature_names, descr):
        self.data = data
        self.target = target
        self.feature_names = feature_names
        self.DESCR = descr
    
    def __repr__(self):
        # Return a complete representation of the object
        return (f"BostonData(\n"
                f"  data={self.data},\n"
                f"  target={self.target},\n"
                f"  feature_names={self.feature_names},\n"
                f"  DESCR={self.DESCR}\n)")

    def keys(self):
        # Return the names of the attributes as a dictionary
        return self.__dict__.keys()

# Instantiate the BostonData object with the data
boston_data = BostonData(data, target, feature_names, descr)
`
