### ISSUE TITLE
Update to sphinx 4.3.0 when released

### ISSUE THREAD

**Issue by ascillitoe** [SeldonIO/alibi#505]
Based on this PR https://github.com/SeldonIO/alibi/pull/482 and this issue https://github.com/sphinx-doc/sphinx/issues/9657 (also see https://github.com/SeldonIO/alibi-detect/pull/338), we should update to `sphinx 4.3.0` as soon as it is released. Opening this issue as a reminder.

**Comment by jklaise** [comment]
Looks like it's out since 10th November!

**Comment by ascillitoe** [comment]
Yay! Looks like it was pulled into `latest` (and `stable` for alibi) as expected:

https://docs.seldon.io/projects/alibi/en/stable/api/alibi.models.pytorch.autoencoder.html

The "Bases:" field looks correct now...
