### ISSUE TITLE
'UnboundLocalError: local variable 'fudged_image' referenced before assignment' in AnchorImage

### ISSUE THREAD

**Issue by ionicsolutions** [SeldonIO/alibi#540]
Providing background images to the `explain` method of `AnchorImage` leads to an `UnboundLocalError`.

Specifically, in [line 257 of the `perturbation` method of `AnchorImageSampler`](https://github.com/SeldonIO/alibi/blob/00f7391132b761b9e28178bbde11ec2eed414ea5/alibi/explainers/anchor_image.py#L257) the variable `fudged_image` has not been defined, because it is only set in [line 235](https://github.com/SeldonIO/alibi/blob/00f7391132b761b9e28178bbde11ec2eed414ea5/alibi/explainers/anchor_image.py#L235) if no background images have been provided.

**Comment by jklaise** [comment]
Thanks for flagging this. Not sure how we missed it and it was even flagged in #460 as a comment on L256. I will work on a fix.

**Comment by jklaise** [comment]
I believe there is an even earlier error in [line 224](https://github.com/SeldonIO/alibi/blob/00f7391132b761b9e28178bbde11ec2eed414ea5/alibi/explainers/anchor_image.py#L224) as the boolean check on a `nupmy` array fails.

**Comment by ionicsolutions** [comment]
> I believe there is an even earlier error in [line 224](https://github.com/SeldonIO/alibi/blob/00f7391132b761b9e28178bbde11ec2eed414ea5/alibi/explainers/anchor_image.py#L224) as the boolean check on a `nupmy` array fails.

I also ran into this error. However, it's possible to provide the background images as a `list` of numpy arrays.

What I found strange when I first looked at the code to figure out whether I might be doing something wrong is [line 250](https://github.com/SeldonIO/alibi/blob/00f7391132b761b9e28178bbde11ec2eed414ea5/alibi/explainers/anchor_image.py#L250). What's the type of `background_idx`? I assume it's an `int` (or compatible), which would mean that the `else` is only ever reached if `background_idx` is `0` but not for any other indices.

Let me know if I can help with fixing/testing/...

**Comment by jklaise** [comment]
@ionicsolutions yes, the code is quite obfuscated which isn't great... Separately, we should fix the issue with being able to provide a `list` but not an array of images.

I believe I know what's going on here, `background_idx` is either an `int` (if `images_background` is passed) or `None` if not (this is set in [line 223](https://github.com/SeldonIO/alibi/blob/00f7391132b761b9e28178bbde11ec2eed414ea5/alibi/explainers/anchor_image.py#L232). So the check `if background_idx` tentatively makes sense as it should distinguish between the two cases of `images_background` passed or not. However, the `else` branch is triggered not only when `background_idx is None` but also when `background_idx==0` which makes it go through the wrong branch and error out as `fudged_image` is not (rightfully) defined.

A fix would be to rewrite the logic so this doesn't happen. The easiest thing might be to check explicitly if `background_idx is None`, but there might be other improvements we can make here. I'll see if I can get round to fixing this later today.
