### ISSUE TITLE
Incorrect links in nbsphinx prolog's

### ISSUE THREAD

**Issue by ascillitoe** [SeldonIO/alibi#553]
The link in nbsphinx prolog's (the "this page was generated from..." messages) in methods pages are broken (but examples seem OK). For example, see below:

![image](https://user-images.githubusercontent.com/32061685/144901168-6aa6c13b-0a88-4d87-96e9-32b7840d7c31.png)

This is occuring in `latest`, but `stable` is OK. The same issue is occurring in `alibi-detect`.

**Comment by jklaise** [comment]
The same issue exists on `alibi-detect` and it looks like after moving examples under `doc/source` those are also affected. Judging from the url it seems to be the path that `readthedocs` server built the docs in.
