### ISSUE TITLE
Support for custom grid point input for ALE

### ISSUE THREAD

**Issue by ryanpmccaffrey** [SeldonIO/alibi#586]
For ALE, instead of computing grid points "under the hood" based on inputs like min_bin_points, it would be great to give users the ability to specify their own custom grid points.  For example, this could be a dictionary with keys being the features and values being the corresponding list of grid points.  This would eliminate the need to calculate quantiles or run the adaptive grid method within the explainer and instead just use the grid points directly.

**Comment by jimbudarz** [comment]
Just for reference, there is a similar feature being enabled in PDP for scikit-learn that might be valuable as inspiration: https://github.com/scikit-learn/scikit-learn/pull/21033

**Comment by jimbudarz** [comment]
Hi @gipster is there any other information that I can provide to help out?

**Comment by jklaise** [comment]
@jimbudarz thanks for the heads-up on the PDP one! We have the PR in the works (#599) would be great to hear if you have any thoughts so we don't miss anything.

**Comment by RobertSamoilescu** [comment]
There are a few cases to consider and we would appreciate some feedback regarding those. 
We will first discuss some notations. Consider `f` to be a feature of interest. We will represent possible feature values of `f` by `X` (i.e. the values from the dataset column corresponding to feature `f`), and by `O` a user-specified grid-point value.

We will illustrate some of the edge cases we've identified:
1) Grid points outside the feature value range. We can illustrate such an example as follows:  `O O O X X O X O X O O`.  We observe that there are 3 grid-points that are smaller than the minimum value in `f`, but also have 2 grid-points that are larger than the maximum value in `f`. Currently, we are clipping the grid-points values in between the minimum and maximum values of `f`. This will look something like `(O|X) X O X O (X|O)`, where `(X|O)` means that the points overlap. An alternative solution would be to keep them and report a value of 0 for ALE in that interval. Feedback is appreciated for this alternative.

2) Grid points that do not cover the entire feature range. For example: `X X O X X O X O X X X X X`. An easy fix would be to add two new grid-points corresponding to the minim and maximum value of feature `f`. This means that it would look something like: `(O|X) X O X X O X O X X X X (X|O)`. The alternative would be to plot the ALE just for the interval specified by the minimum and maximum grid point. This would be: `O X X O X O`. Feedback is appreciated for this alternative.

3) Grid points that do not contain any values in between. For example `(O|X) X X O O O X O X O O (X|O)`. We can remove the intervals which do not contain any feature values and obtain something like this: (O|X) X X O X O X O (X|O)`. The alternative would be to keep them and report a value of 0 for those intervals. This can result in some flat regions in the plot. Feedback is also appreciated.

Some side notes:
* Every modification of the original grid-point would be logged for transparency.
* I believe that some flat regions, even if not plotted, can be inferred by looking at the feature distribution (i.e., zero density regions can be considered as flat regions).

@ryanpmccaffrey, @jimbudarz we would really appreciate some feedback on those edge cases to better understand what is the expected and most informative behavior for your application.

**Comment by jimbudarz** [comment]
Thanks for looping me in.

In general, I would trust that the user has provided values because they have a region of interest. 

In our case, we'd like to use larger datasets, which require distributing rows across multiple workers. To do this, we need a consistent set of points across workers and so the max/min need to be globally-consistent, not just on the rows available to a worker.

**Comment by ryanpmccaffrey** [comment]
Hi @RobertSamoilescu @jklaise, thank you both for your responsiveness and diligence.  For all three edge cases I think your proposed default behavior seems appropriate.  In full transparency, @jimbudarz and I are both no longer working on the project that will benefit from these custom grid point changes.  Sorry for my delayed response and thanks for the update.
