### ISSUE TITLE
Examples of black box models for counterfactual guided by prototypes

### ISSUE THREAD

**Issue by neilm1** [SeldonIO/alibi#598]
I would like to use the guided prototypes methods to try and explain Random Forest and XGBoost models (and compare with the performance of DICE). Are there any examples notebooks of black box models as the only examples I have seen as based on tensor flow.

**Comment by neilm1** [comment]
Found the example

**Comment by mauicv** [comment]
Hey @neilm1,
Just so you are aware the counterfactuals guided by prototypes method assumes that the underlying model is differentiable which isn't the case for tree-based models.
