### ISSUE TITLE
'multidim_scaling' with inconsistent parameter 'feature_range' for tuple of floats

### ISSUE THREAD

**Issue by JEwerszumrode** [SeldonIO/alibi#642]
As in the docstring of the [multidim_scaling](https://github.com/SeldonIO/alibi/blob/6ce8a51c30041cfaaf656abab0c1202a05284cf3/alibi/utils/distance.py#L164) utils function it is said, that the parameter `feature_range` can be tuple of floats:
```
def  multidim_scaling(...):
   ...
   feature_range
        Tuple with `min` and `max` ranges to allow for perturbed instances. `Min` and `max` ranges can be `float` or
        `numpy` arrays with dimension (`1 x nb of features`) for feature-wise ranges.
```

But some lines later you used to copy each element of the tuble by `new_feature_range = tuple([f.copy() for f in feature_range])`
which yields to comprehensible error of `'float' object has no attribute 'copy'`

This is also used in [CounterfactualsProto](https://github.com/SeldonIO/alibi/blob/1fd0e797a78007d7a0ec8082e12185b9fa731201/alibi/explainers/cfproto.py#L41) as default:
```
class CounterfactualProto(...):
    def __init__(..., feature_range: tuple = (-1e10, 1e10), ...)
```

**Comment by jklaise** [comment]
Fixed in #646.
