### ISSUE TITLE
Clean up documentation page sidebar

### ISSUE THREAD

**Issue by jklaise** [SeldonIO/alibi#658]
As the number of examples has exploded, the organisation of them in the documentation page sidebar without sections has become unwieldy. We should do something similar to the [Alibi Detect docs](https://docs.seldon.io/projects/alibi-detect/en/stable/).

**Important:** we should make our best efforts to not just remove the old link paths to avoid "breaking the internet". This should be ok as looking at Alibi Detect, the example notebook paths all remain unchanged, they're just grouped into the new "example grouping" pages.

**Comment by ascillitoe** [comment]
Totally agree!

As you say, this was done for detect by moving examples (and overview pages) under their relevant `cd/`, `od/`, `ad/` folders, and then adding separate `toctree`'s to `index.md`:

````md
```{toctree}
:caption: Outlier Detection
:maxdepth: 2

od/methods
od/examples
```

```{toctree}
:caption: Drift Detection
:maxdepth: 2

cd/background
cd/methods
cd/examples
```

```{toctree}
:caption: Adversarial Detection
:maxdepth: 2

ad/methods
ad/examples
```
````

Happy to do if/when you've decided on the groupings...

**Comment by jklaise** [comment]
As part of this we should clean up the landing page as the highest-level heading is "Indices and tables" which becomes the title of the whole page. C.f. how it's handled in Alibi Detect.

**Comment by jklaise** [comment]
Closing as was done for the `0.7.0` release.
