### ISSUE TITLE
Update AnchorTabular precision warning

### ISSUE THREAD

**Issue by RobertSamoilescu** [SeldonIO/alibi#699]
There exists an edge-case where the Anchor algorithm cannot find a set of predicates that satisfy the precision constraint. This warning is specific for the `AnchorTabadditionalular` because of the numerical discretisation. For numerical features, the values are sampled from the corresponding intervals defined by the discretisation method (i.e. quantiles). Given a numerical feature `f` in the interval `[a, b]` obtained after discretisation, there might be the case that the prediction of the model is 1 (same as the input instance) for 70% of the values in `[a, b]`, and 0 for the remaining 30%. Thus, it is possible that we cannot find an anchor that satisfies, for example, a precision threshold of 95%.

It would be great if for `AnchorTabular` we might extend the warning message so it includes some additional justification of why it might be impossible to find an anchor that satisfies the precision constraint. In addition we would like to document well this edge-case in our docs. Right now the warring belongs to the [base class](https://github.com/SeldonIO/alibi/blob/e5814a814aecb81141f9a856beb18772e93fcdcf/alibi/explainers/anchors/anchor_base.py#L792-L794).

**Comment by jklaise** [comment]
Resolved via #711.
