### ISSUE TITLE
AnchorImage  slic start_label=1  by default

### ISSUE THREAD

**Issue by RobertSamoilescu** [SeldonIO/alibi#748]
The current `AnchorImage` implementation assumes that the segmentation labels start at 0. The logic can be seen [here](https://github.com/SeldonIO/alibi/blob/711bc1697cc5b6876b95254116c49ea9665a791d/alibi/explainers/anchors/anchor_image.py#L251-L257):

* first, the algorithm identifies the superpixels to be perturbed by checking where the `mask` is 0. This will return an array of values between 0 and K - 1 (including 0 and K-1), where K is the number of superpixels. The results is stored in `to_perturb`.
* the values in `to_perturbed` are compared with the values in the segmentation mask (i.e., `segments == superpixel`, where `superpixels` is an iterator over `to_perturb`). This assumes that the values of `segments`  are also between 0 and K-1.

It seems that from version 0.19.x the default value of the `start_label`  in the segmentation mask returned by `slic` became 1 which contradicts the anchor sampler assumptions. I believe this means that one superpixel will not be perturbed.  For more info see the PR [here](https://github.com/scikit-image/scikit-image/pull/6242).

There are two possible solution:
* update the `slic` `kwargs` and linclude `'start_label': 0`. This will require to bump the version of `skimage` to 0.17.x 
* update the internal logic to be agnostic to the values in the segmentation mask.

**Comment by jklaise** [comment]
We should also check if it's true that other segmentation methods we use from `skimage` already return segments labelled starting with `1` as this may have an effect of which superpixels we ultimately perturb dependent on the segmentation function (we could have an off-by-one error if other methods return labelling `1,...,K` as we wouldn't then perturb the `K`th segment).

**Comment by RobertSamoilescu** [comment]
The other two methods [here](https://github.com/SeldonIO/alibi/blob/711bc1697cc5b6876b95254116c49ea9665a791d/alibi/explainers/anchors/anchor_image.py#L20-L24) return segments labels starting from 0. 

I guess the only problem is when a segmentation function, possible user specified, does not respect the expected labelling convention.

**Comment by jklaise** [comment]
Closed via #753.
