### ISSUE TITLE
Typo in TreeShap documentation

### ISSUE THREAD

**Issue by valeriy42** [SeldonIO/alibi#806]
In the [TreeShap documentation](https://docs.seldon.io/projects/alibi/en/stable/methods/TreeSHAP.html) the parameter should be `cat_vars_start_idx` and not `cat_var_start_idx`. Since the code uses `kwargs.get()`, the typo gets unnoticed until one debugs.

**Comment by mauicv** [comment]
Hey @valeriy42,
Thank you very much for pointing this out!

I'm a little confused about the latter point though. The `TreeShap` [explain method declares](https://github.com/SeldonIO/alibi/blob/431290797ff710bf17cd3b7bece7e16e4f39b078/alibi/explainers/shap_wrappers.py#L1258) `cat_vars_start_idx` as a parameter?

**Comment by valeriy42** [comment]
Closed in #807
