### ISSUE TITLE
[BUG] 'TfCounterfactualRLDataset' object has no attribute 'max_m' in line 99 because of a typo in definition line 73

### ISSUE THREAD

**Issue by zlds123** [SeldonIO/alibi#885]
https://github.com/SeldonIO/alibi/blob/3594f71c809225300679722b054f48846cfae948/alibi/explainers/backends/tensorflow/cfrl_base.py#L73

Should be max_m not max_n

**Comment by RobertSamoilescu** [comment]
@zlds123, thank you for pointing this out!
Would you like to do a PR to fix it?
