### ISSUE TITLE
ALE uses deprecated "np.object" and raises AttributeError

### ISSUE THREAD

**Issue by leoncena** [SeldonIO/alibi#888]
Hello,
ALE returns following error. I assume it needs to be changed to "object" since it is deprecated  in numpy 1.20. I saw a similar thing in another PR (https://github.com/SeldonIO/alibi/pull/872).

Error (when trying to plot ale):
AttributeError: module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe. 
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations 

Kind regards

**Comment by jklaise** [comment]
Thank you for reporting this. In fact, there are 3 places we use `np.object` - all in plotting code. We missed this as one of our extra dependencies on CI limit the `numpy` version to 1.23.x whereas the newest versions completely remove `np.object` resulting in an error.

I will submit a fix and release a patch today.

**Comment by jklaise** [comment]
@leoncena version 0.9.1 is now released fixing the bug.
